/*PRE-BUILD*/
DROP SEQUENCE tag_id_seq ;
DROP TABLE TAGS  CASCADE CONSTRAINTS ; 
DROP TABLE ASSETS  CASCADE CONSTRAINTS ; 
DROP TABLE  DOCS  CASCADE CONSTRAINTS ; 
DROP TABLE  DOC_TYPES  CASCADE CONSTRAINTS ; 
DROP TABLE ENGR_DISC  CASCADE CONSTRAINTS ; 
DROP TABLE COMM_DISC CASCADE CONSTRAINTS ; 
DROP TABLE OPS_DISC CASCADE CONSTRAINTS ; 
DROP TABLE COMM_SYS CASCADE CONSTRAINTS ; 
DROP TABLE TAG_AREAS  CASCADE CONSTRAINTS ; 
DROP TABLE TAG_CLASSES  CASCADE CONSTRAINTS ; 
DROP TABLE TAG_TO_DOC  CASCADE CONSTRAINTS ; 
DROP TABLE TAG_TO_EQUIP CASCADE CONSTRAINTS ; 
DROP TABLE TAG_TO_TAG  CASCADE CONSTRAINTS ; 
DROP TABLE TAG_DETAILS_I CASCADE CONSTRAINTS ; 
DROP TABLE TAG_DETAILS_SP CASCADE CONSTRAINTS ; 
DROP TABLE TAG_DETAILS_C  CASCADE CONSTRAINTS ; 
DROP TABLE TAG_DETAILS_ZENATOR CASCADE CONSTRAINTS ; 
DROP TABLE TAG_DETAILS_E CASCADE CONSTRAINTS ; 
DROP TABLE TAG_DETAILS_P CASCADE CONSTRAINTS ; 
DROP TABLE TAG_DETAILS_T CASCADE CONSTRAINTS ; 
DROP TABLE TAG_DETAILS_M CASCADE CONSTRAINTS ; 

CREATE SEQUENCE tag_id_seq START WITH 1 INCREMENT BY 1;

/* FACTS        */
/* Tagged items */
CREATE TABLE TAGS (
ID  NUMBER NOT NULL PRIMARY KEY, 
IDENTIFIER          VARCHAR2 ( 4000 CHAR ) NOT NULL UNIQUE, 
NAME                 VARCHAR2 ( 4000 CHAR ), -- "Tag Name"
SVC_DESCRIPTION      VARCHAR2 ( 4000 CHAR ),
TAG_AREA_ID          NUMBER, -- NN FK
COMM_CLASS_ID        NUMBER, -- NN FK
COMM_DISC_ID         NUMBER, -- NN FK
ENGR_DISC_ID         NUMBER, -- NN FK
OPS_DISC_ID          NUMBER, -- NN FK
COMM_SYS_ID          NUMBER, -- NN FK
IS_VEND_ITEM         NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_VEND_ITEM IN ( 0 , 1 ) ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ) 
);

CREATE TRIGGER tags_tr_bifer
BEFORE INSERT ON tags
FOR EACH ROW
BEGIN :NEW.ID := tag_id_seq.nextval;
END;
/


/* ASSETS    */
CREATE TABLE ASSETS (
ID  NUMBER NOT NULL PRIMARY KEY, 
IDENTIFIER          VARCHAR2 ( 4000 CHAR ) NOT NULL UNIQUE, 
MFG                            VARCHAR2 ( 4000 CHAR ),
MFG_DATE                       DATE,
MFG_MODEL_NO                   VARCHAR2 ( 4000 CHAR ),
MFG_PART_NO                    VARCHAR2 ( 4000 CHAR ),
MFG_SERIAL_NO                  VARCHAR2 ( 4000 CHAR ),
VEND                           VARCHAR2 ( 4000 CHAR ),
VEND_MODEL_NO                  VARCHAR2 ( 4000 CHAR ),
VEND_PART_NO                   VARCHAR2 ( 4000 CHAR ),
VEND_SERIAL_NO                 VARCHAR2 ( 4000 CHAR ),
INSTALLED_BY                   VARCHAR2 ( 4000 CHAR ),
MAINTAINED_BY                  VARCHAR2 ( 4000 CHAR ),
PURCHASE_DATE                  DATE,
PURCHASE_COST                  NUMBER,
PURCHASE_COST_UOM              VARCHAR2 ( 4000 CHAR ),
REPLACEMENT_COST               NUMBER,
REPLACEMENT_COST_UOM           VARCHAR2 ( 4000 CHAR ),
PO_NO                          VARCHAR2 ( 4000 CHAR ),
WARRANTY_EFFECTIVE_ON          DATE,
WARRANTY_EXPIRES_ON            DATE
);

/* DOCUMENTS */
CREATE TABLE docs (
ID  NUMBER NOT NULL PRIMARY KEY, 
IDENTIFIER          VARCHAR2 ( 4000 CHAR ) NOT NULL UNIQUE, 
doc_type_id         NUMBER,
title               VARCHAR2 ( 4000 CHAR ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ) 
) ; 

/* MANAGED DIMENSION     */
/* Document types        */
CREATE TABLE DOC_TYPES (
ID  NUMBER NOT NULL PRIMARY KEY, 
IDENTIFIER          VARCHAR2 ( 4000 CHAR ) NOT NULL UNIQUE, 
DESCRIPTION       VARCHAR2 ( 4000 CHAR ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ) 
) ; 

/* MANAGED DIMENSION         */
/* Engineering disciplines */
CREATE TABLE ENGR_DISC (
ID  NUMBER NOT NULL PRIMARY KEY, 
IDENTIFIER          VARCHAR2 ( 4000 CHAR ) NOT NULL UNIQUE, 
DESCRIPTION       VARCHAR2 ( 4000 CHAR ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ) 
) ; 

/* MANAGED DIMENSION         */
/* Commissioning disciplines */
CREATE TABLE COMM_DISC (
ID  NUMBER NOT NULL PRIMARY KEY, 
IDENTIFIER          VARCHAR2 ( 4000 CHAR ) NOT NULL UNIQUE, 
DESCRIPTION       VARCHAR2 ( 4000 CHAR ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ) 
) ; 

/* MANAGED DIMENSION         */
/* Operations disciplines */
CREATE TABLE OPS_DISC (
ID  NUMBER NOT NULL PRIMARY KEY, 
IDENTIFIER          VARCHAR2 ( 4000 CHAR ) NOT NULL UNIQUE, 
DESCRIPTION       VARCHAR2 ( 4000 CHAR ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ) 
) ; 

/* MANAGED DIMENSION     */
/* Commissioning systems */
CREATE TABLE COMM_SYS (
ID  NUMBER NOT NULL PRIMARY KEY, 
IDENTIFIER          VARCHAR2 ( 4000 CHAR ) NOT NULL UNIQUE, 
PARENT_ID         NUMBER, -- NN FK
--PARENT_IDENTIFIER VARCHAR2 ( 4000 CHAR ), -- NN FK
DESCRIPTION       VARCHAR2 ( 4000 CHAR ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ) 
) ; 

/* PROJECT AREAS         */
/* MANAGED DIMENSION     */
CREATE TABLE TAG_AREAS (
ID  NUMBER NOT NULL PRIMARY KEY, 
IDENTIFIER          VARCHAR2 ( 4000 CHAR ) NOT NULL UNIQUE, 
PARENT_ID         NUMBER, 
DESCRIPTION       VARCHAR2 ( 4000 CHAR ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ) 
) ; 

/* TAG CLASSES - MANAGED DIMENSION */
CREATE TABLE TAG_CLASSES (
ID  NUMBER NOT NULL PRIMARY KEY, 
IDENTIFIER          VARCHAR2 ( 4000 CHAR ) NOT NULL UNIQUE, 
PARENT_ID NUMBER, 
DESCRIPTION VARCHAR2 ( 4000 CHAR ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ) 
) ; 


/* TAG TO DOCUMENT - RELATIONS */
CREATE TABLE TAG_TO_DOC ( 
ID  NUMBER NOT NULL PRIMARY KEY, 
TAG_ID NUMBER NOT NULL REFERENCES TAGS ( ID ),
DOC_ID NUMBER NOT NULL REFERENCES DOCS ( ID ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ) 
);

/* TAG TO ASSET - RELATIONS */
CREATE TABLE TAG_TO_EQUIP ( 
ID  NUMBER NOT NULL PRIMARY KEY, 
TAG_ID NUMBER NOT NULL REFERENCES TAGS ( ID ),
ASSET_ID NUMBER NOT NULL REFERENCES ASSETS ( ID ),
IS_INSTALLED NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_INSTALLED IN ( 0 , 1 ) ),
IS_SPARE NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_SPARE IN ( 0 , 1 ) ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ) 
);

/* RELATIONS    */
/* Tag to tag   */
CREATE TABLE TAG_TO_TAG ( 
ID  NUMBER NOT NULL PRIMARY KEY, 
TAG_ID NUMBER NOT NULL REFERENCES TAGS ( ID ),
PARENT_TAG_ID NUMBER NOT NULL REFERENCES TAGS ( ID ),
RELATION_TYPE VARCHAR2 ( 4000 CHAR ) NOT NULL CHECK ( RELATION_TYPE IN ( 'PHYSICAL','FUNCTIONAL','PACKAGE') ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ),
CONSTRAINT TAG_TO_DOC_UK_01 UNIQUE ( TAG_ID, PARENT_TAG_ID )
 );
 
 /* DIMENSION              */
/* Instrument tag details */
CREATE TABLE TAG_DETAILS_I ( 
ID  NUMBER NOT NULL PRIMARY KEY, 
TAG_ID                        NUMBER NOT NULL REFERENCES TAGS ( ID ),
ANSI_LEAK_CLASS               VARCHAR2 ( 4000 CHAR ),
AREA_CLASSIFICATION           VARCHAR2 ( 4000 CHAR ),
BACK_PRESSURE                 VARCHAR2 ( 4000 CHAR ),
BACK_PRESSURE_UOM             VARCHAR2 ( 4000 CHAR ),
BENCH_SETTING                 VARCHAR2 ( 4000 CHAR ),
BURSTING_PRESSURE             VARCHAR2 ( 4000 CHAR ),
BURSTING_PRESSURE_UOM         VARCHAR2 ( 4000 CHAR ),
CALIBRATED_RANGE              VARCHAR2 ( 4000 CHAR ),
CALIBRATED_RANGE_MAX          VARCHAR2 ( 4000 CHAR ),
CALIBRATED_RANGE_MAX_UOM      VARCHAR2 ( 4000 CHAR ),
CALIBRATED_RANGE_MIN          VARCHAR2 ( 4000 CHAR ),
CALIBRATED_RANGE_MIN_UOM      VARCHAR2 ( 4000 CHAR ),
CALIBRATED_RANGE_UFLG_MAX     VARCHAR2 ( 4000 CHAR ),
CALIBRATED_RANGE_UFLG_MIN     VARCHAR2 ( 4000 CHAR ),
CALIBRATED_RANGE_UOM          VARCHAR2 ( 4000 CHAR ),
CALIBRATION_CERTIFICATE_NO    VARCHAR2 ( 4000 CHAR ),
CALIBRATION_DATE              VARCHAR2 ( 4000 CHAR ),
CASE_NAME                     VARCHAR2 ( 4000 CHAR ),
CAUSE_AND_EFFECT_DIAGRAM      VARCHAR2 ( 4000 CHAR ),
CERTIFICATION_DATE            VARCHAR2 ( 4000 CHAR ),
CERTIFYING_AUTHORITY          VARCHAR2 ( 4000 CHAR ),
CERTIFYING_NO                 VARCHAR2 ( 4000 CHAR ),
CMPNT_ID                      VARCHAR2 ( 4000 CHAR ),
COLD_SET_PRESSURE             VARCHAR2 ( 4000 CHAR ),
COLD_SET_PRESSURE_UOM         VARCHAR2 ( 4000 CHAR ),
COLD_SET_PRESS_UOM            VARCHAR2 ( 4000 CHAR ),
CONTROL_SYSTEM                VARCHAR2 ( 4000 CHAR ),
CORROSION_GROUP               VARCHAR2 ( 4000 CHAR ),
CRITICALITY_RATING            VARCHAR2 ( 4000 CHAR ),
DATA_SHEET                    VARCHAR2 ( 4000 CHAR ),
DELETED_FLAG                  VARCHAR2 ( 4000 CHAR ),
DESIGN_SETTING                VARCHAR2 ( 4000 CHAR ),
DESIGN_SETTING_UOM            VARCHAR2 ( 4000 CHAR ),
DETECTOR_RANGE                VARCHAR2 ( 4000 CHAR ),
DETECTOR_RANGE_UOM            VARCHAR2 ( 4000 CHAR ),
DETECTOR_SENSITIVITY          VARCHAR2 ( 4000 CHAR ),
DETECTOR_SENSITIVITY_UOM      VARCHAR2 ( 4000 CHAR ),
DIGITAL_STANDARD              VARCHAR2 ( 4000 CHAR ),
EQUIPMENT_LEVEL_A_C           VARCHAR2 ( 4000 CHAR ),
EQUIPMENT_PARTS_LIST          VARCHAR2 ( 4000 CHAR ),
DOC_FIRE_AND_GAS_CONTROL_SCM  VARCHAR2 ( 4000 CHAR ),
FUTURE_FLAG                   VARCHAR2 ( 4000 CHAR ),
GASKET                        VARCHAR2 ( 4000 CHAR ),
GASKET_TYPE                   VARCHAR2 ( 4000 CHAR ),
HAZARDOUS_AREA_CLASSIFICATION VARCHAR2 ( 4000 CHAR ),
INGRESS_PROTECTION            VARCHAR2 ( 4000 CHAR ),
INGRESS_PROTECTION_RATING     VARCHAR2 ( 4000 CHAR ),
DOC_INSTALLATION_DTL          VARCHAR2 ( 4000 CHAR ),
INST_TYPE                     VARCHAR2 ( 4000 CHAR ),
INST_TYPE_DESCRIPTION         VARCHAR2 ( 4000 CHAR ),
DOC_ISOLATION_PROCEDURE       VARCHAR2 ( 4000 CHAR ),
I_O_LOCATION                  VARCHAR2 ( 4000 CHAR ),
I_O_TYPE                      VARCHAR2 ( 4000 CHAR ),
LIFTING_DRAWING               VARCHAR2 ( 4000 CHAR ),
LOCATION                      VARCHAR2 ( 4000 CHAR ),
LOCATION_PLAN                 VARCHAR2 ( 4000 CHAR ),
LOC_PLAN                      VARCHAR2 ( 4000 CHAR ),
LOGIC_DIAGRAM                 VARCHAR2 ( 4000 CHAR ),
LOOP_DIAGRAM                  VARCHAR2 ( 4000 CHAR ),
LOOP_DRAWING                  VARCHAR2 ( 4000 CHAR ),
MANUFACTURER                  VARCHAR2 ( 4000 CHAR ),
MANUFACTURER_MODEL_NO         VARCHAR2 ( 4000 CHAR ),
MANUFACTURER_NAME             VARCHAR2 ( 4000 CHAR ),
MAXIMUM_TEST_PRESSURE         VARCHAR2 ( 4000 CHAR ),
MAXIMUM_TEST_PRESSURE_UOM     VARCHAR2 ( 4000 CHAR ),
MECHANICAL_CONNECTIONS        VARCHAR2 ( 4000 CHAR ),
MODEL_NO                      VARCHAR2 ( 4000 CHAR ),
OLD_TAG_NO                    VARCHAR2 ( 4000 CHAR ),
OPERATING_TIME_TO_CLOSE       VARCHAR2 ( 4000 CHAR ),
OPERATING_TIME_TO_OPEN        VARCHAR2 ( 4000 CHAR ),
DOC_IOM                       VARCHAR2 ( 4000 CHAR ),
DOC_PID                       VARCHAR2 ( 4000 CHAR ),
OUTPUT                        VARCHAR2 ( 4000 CHAR ),
OUTPUT_RANGE                  VARCHAR2 ( 4000 CHAR ),
OUTPUT_RANGE_UOM              VARCHAR2 ( 4000 CHAR ),
OUTPUT_UOM                    VARCHAR2 ( 4000 CHAR ),
PACKAGE_TAG                   VARCHAR2 ( 4000 CHAR ),
PARENT_TAG                    VARCHAR2 ( 4000 CHAR ),
PNEU_DET                      VARCHAR2 ( 4000 CHAR ),
PO_NO                         VARCHAR2 ( 4000 CHAR ),
PRESSURE_RELIEVING_DEVICE     VARCHAR2 ( 4000 CHAR ),
PROCESS_FUNCTION              VARCHAR2 ( 4000 CHAR ),
PROC_DET                      VARCHAR2 ( 4000 CHAR ),
PURCHASE_ORDER_NO             VARCHAR2 ( 4000 CHAR ),
RECOMMENDED_SPARE_PARTS_LIST  VARCHAR2 ( 4000 CHAR ),
RELIEVING_SET_POINT           VARCHAR2 ( 4000 CHAR ),
RELIEVING_SET_POINT_UOM       VARCHAR2 ( 4000 CHAR ),
SEGMENT_DRAWING               VARCHAR2 ( 4000 CHAR ),
SERIAL_NO                     VARCHAR2 ( 4000 CHAR ),
SERVICE_DESCRIPTION           VARCHAR2 ( 4000 CHAR ),
SET_POINT_HIGH                VARCHAR2 ( 4000 CHAR ),
SET_POINT_LOW                 VARCHAR2 ( 4000 CHAR ),
SET_POINT_UOM                 VARCHAR2 ( 4000 CHAR ),
SET_PRESSURE                  VARCHAR2 ( 4000 CHAR ),
SET_PRESSURE_UOM              VARCHAR2 ( 4000 CHAR ),
SET_PRESS_FLAG                VARCHAR2 ( 4000 CHAR ),
SIL_LEVEL                     VARCHAR2 ( 4000 CHAR ),
SPAN                          VARCHAR2 ( 4000 CHAR ),
SPAN_UOM                      VARCHAR2 ( 4000 CHAR ),
SPECIAL_TOOLS_LIST            VARCHAR2 ( 4000 CHAR ),
SUB_LOCATION                  VARCHAR2 ( 4000 CHAR ),
SUB_SYSTEM                    VARCHAR2 ( 4000 CHAR ),
SUPPT_DET                     VARCHAR2 ( 4000 CHAR ),
TAG_DATA_SOURCE_ID            VARCHAR2 ( 4000 CHAR ),
DOC_TERMINATION_DWG           VARCHAR2 ( 4000 CHAR ),
VALVE_ACTION_ON_FAILURE       VARCHAR2 ( 4000 CHAR ),
VALVE_TRAVEL                  VARCHAR2 ( 4000 CHAR ),
VALVE_TRAVEL_UOM              VARCHAR2 ( 4000 CHAR ),
VENDOR                        VARCHAR2 ( 4000 CHAR ),
VENDOR_FLAG                   VARCHAR2 ( 4000 CHAR ),
VENDOR_ITEM                   VARCHAR2 ( 4000 CHAR ),
VENDOR_MODEL_NO               VARCHAR2 ( 4000 CHAR ),
VOLTAGE_RATING                VARCHAR2 ( 4000 CHAR ),
VOLTAGE_RATING_UOM            VARCHAR2 ( 4000 CHAR ),
WARRANTY_EXPIRATION           VARCHAR2 ( 4000 CHAR )
);

/* DIMENSION                   */
/* Speciality item tag details */
CREATE TABLE TAG_DETAILS_SP (
ID  NUMBER NOT NULL PRIMARY KEY, 
TAG_ID               NUMBER NOT NULL REFERENCES TAGS ( ID ),
SMARTPLANT_ID        VARCHAR2 ( 4000 CHAR ),
PLANT_GROUP          VARCHAR2 ( 4000 CHAR ),
DOC_PID              VARCHAR2 ( 4000 CHAR ),
WBS_CODE             VARCHAR2 ( 4000 CHAR ),
LINE_NO              VARCHAR2 ( 4000 CHAR ),
NOMINAL_SIZE         VARCHAR2 ( 4000 CHAR ),
NOMINAL_SIZE_UOM     VARCHAR2 ( 4000 CHAR ),
PIPE_SPEC            VARCHAR2 ( 4000 CHAR ),
PIPING_COMP_PREFIX   VARCHAR2 ( 4000 CHAR ),
SP_SEQUENCE_NO       VARCHAR2 ( 4000 CHAR ),
DESCRIPTION          VARCHAR2 ( 4000 CHAR ),
SUPPLIED_BY          VARCHAR2 ( 4000 CHAR ),
IS_VENDOR_ITEM       VARCHAR2 ( 4000 CHAR ),
OE_PROCESS_STATUS    VARCHAR2 ( 4000 CHAR ),
COMMENTS             VARCHAR2 ( 4000 CHAR ),
X_COORDINATE         VARCHAR2 ( 4000 CHAR ),
Y_COORDINATE         VARCHAR2 ( 4000 CHAR )
);

/* DIMENSION                   */
/* Cable tag details           */
CREATE TABLE TAG_DETAILS_C (
ID  NUMBER NOT NULL PRIMARY KEY, 
TAG_ID                             NUMBER NOT NULL REFERENCES TAGS ( ID ),
CABLE_SPECIFICATION                VARCHAR2 ( 4000 CHAR ),
CORROSION_GROUP                    VARCHAR2 ( 4000 CHAR ),
CRITICALITY_RATING                 VARCHAR2 ( 4000 CHAR ),
CROSS_SECTIONAL_AREA               VARCHAR2 ( 4000 CHAR ),
CROSS_SECTIONAL_AREA_UOM           VARCHAR2 ( 4000 CHAR ),
DATA_SHEET                         VARCHAR2 ( 4000 CHAR ),
DELETED_FLAG                       VARCHAR2 ( 4000 CHAR ),
EQUIPMENT_CLASSIFICATION           VARCHAR2 ( 4000 CHAR ),
EQUIPMENT_PARTS_LIST               VARCHAR2 ( 4000 CHAR ),
EQUIPMENT_SUBCLASSIFICATION        VARCHAR2 ( 4000 CHAR ),
ESTIMATED_LENGTH                   VARCHAR2 ( 4000 CHAR ),
ESTIMATED_LENGTH_UOM               VARCHAR2 ( 4000 CHAR ),
FROM_GLAND                         VARCHAR2 ( 4000 CHAR ),
FROM_LOCATION                      VARCHAR2 ( 4000 CHAR ),
FROM_TAG                           VARCHAR2 ( 4000 CHAR ),
FROM_TERMINATION_DRAWING           VARCHAR2 ( 4000 CHAR ),
IS_INTRINSICALLY_SAFE              VARCHAR2 ( 4000 CHAR ),
DOC_LIFTING_DWG                    VARCHAR2 ( 4000 CHAR ),
LOCATION                           VARCHAR2 ( 4000 CHAR ),
LOCATION_PLAN                      VARCHAR2 ( 4000 CHAR ),
MANUFACTURER                       VARCHAR2 ( 4000 CHAR ),
MANUFACTURER_MODEL_NUMBER          VARCHAR2 ( 4000 CHAR ),
NUMBER_OF_CORES                    VARCHAR2 ( 4000 CHAR ),
OLD_CABLE_NUMBER                   VARCHAR2 ( 4000 CHAR ),
PACKAGE_TAG                        VARCHAR2 ( 4000 CHAR ),
PARENT_TAG                         VARCHAR2 ( 4000 CHAR ),
PURCHASE_ORDER_NUMBER              VARCHAR2 ( 4000 CHAR ),
RECOMMENDED_SPARE_PARTS_LIST       VARCHAR2 ( 4000 CHAR ),
SERVICE_DESCRIPTION                VARCHAR2 ( 4000 CHAR ),
NOMINAL_SIZE                       VARCHAR2 ( 4000 CHAR ),
NOMINAL_SIZE_UOM                   VARCHAR2 ( 4000 CHAR ),
SUBSYSTEM                          VARCHAR2 ( 4000 CHAR ),
SUB_LOCATION                       VARCHAR2 ( 4000 CHAR ),
SYSTEM                             VARCHAR2 ( 4000 CHAR ),
SYSTEM_THAT_CABLE_IS_PART_OF       VARCHAR2 ( 4000 CHAR ),
TO_GLAND                           VARCHAR2 ( 4000 CHAR ),
TO_LOCATION                        VARCHAR2 ( 4000 CHAR ),
TO_TAG                             VARCHAR2 ( 4000 CHAR ),
TO_TERMINATION_DRAWING             VARCHAR2 ( 4000 CHAR ),
TYPE_OF_SIGNAL_CARRIED             VARCHAR2 ( 4000 CHAR ),
VENDOR                             VARCHAR2 ( 4000 CHAR ),
VENDOR_ITEM                        VARCHAR2 ( 4000 CHAR ),
VENDOR_MODEL_NUMBER                VARCHAR2 ( 4000 CHAR ),
VOLTAGE                            VARCHAR2 ( 4000 CHAR ),
VOLTAGE_UOM                        VARCHAR2 ( 4000 CHAR )
);

/* DIMENSION                        */
/* General tag details from Zenator */
CREATE TABLE TAG_DETAILS_ZENATOR (
ID  NUMBER NOT NULL PRIMARY KEY, 
TAG_ID                   NUMBER NOT NULL REFERENCES TAGS ( ID ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ), 
AREA                     VARCHAR2 ( 4000 CHAR ),
AREA_CLASSIFICATION      VARCHAR2 ( 4000 CHAR ),
ASSIGNED_AITR            VARCHAR2 ( 4000 CHAR ),
ASSIGNED_BITR            VARCHAR2 ( 4000 CHAR ),
ASSIGNED_PITR            VARCHAR2 ( 4000 CHAR ),
A_ITR_LIST               VARCHAR2 ( 4000 CHAR ),
A_ITR_STATUS             VARCHAR2 ( 4000 CHAR ),
B_ITR_LIST               VARCHAR2 ( 4000 CHAR ),
B_ITR_STATUS             VARCHAR2 ( 4000 CHAR ),
CAUSE_AND_EFFECT_DRAWING VARCHAR2 ( 4000 CHAR ),
CIRCUIT_NO               VARCHAR2 ( 4000 CHAR ),
CONTRACT                 VARCHAR2 ( 4000 CHAR ),
DATA_SOURCE              VARCHAR2 ( 4000 CHAR ),
DATE_CREATED             VARCHAR2 ( 4000 CHAR ),
DISCIPLINE               VARCHAR2 ( 4000 CHAR ),
DISTRIBUTION_BOARD       VARCHAR2 ( 4000 CHAR ),
FROM_DESCRIPTION         VARCHAR2 ( 4000 CHAR ),
FROM_DRAWING             VARCHAR2 ( 4000 CHAR ),
FROM_TAG                 VARCHAR2 ( 4000 CHAR ),
GA_DRAWING               VARCHAR2 ( 4000 CHAR ),
HANDOVER                 VARCHAR2 ( 4000 CHAR ),
IMPORT_TEMPLATE          VARCHAR2 ( 4000 CHAR ),
INSTALLATION_DETAIL      VARCHAR2 ( 4000 CHAR ),
LOCATION_PLAN            VARCHAR2 ( 4000 CHAR ),
LOOP_DIAGRAM_REFERENCE   VARCHAR2 ( 4000 CHAR ),
LOOP_NO                  VARCHAR2 ( 4000 CHAR ),
MAINTAINABLE             VARCHAR2 ( 4000 CHAR ),
MAIN_PROJECT             VARCHAR2 ( 4000 CHAR ),
MANUFACTURER             VARCHAR2 ( 4000 CHAR ),
MODULE                   VARCHAR2 ( 4000 CHAR ),
PACKAGE_NO               VARCHAR2 ( 4000 CHAR ),
PARENT_SKID              VARCHAR2 ( 4000 CHAR ),
PARENT_TAG               VARCHAR2 ( 4000 CHAR ),
PARENT_TAG_NAME          VARCHAR2 ( 4000 CHAR ),
PHYSICAL_LOCATION        VARCHAR2 ( 4000 CHAR ),
PO_NO                    VARCHAR2 ( 4000 CHAR ),
PRIMARY_DRAWING          VARCHAR2 ( 4000 CHAR ),
PRIMARY_VENDOR_DRAWING   VARCHAR2 ( 4000 CHAR ),
PROJECT_GROUP_NO         VARCHAR2 ( 4000 CHAR ),
PROJECT_NAME             VARCHAR2 ( 4000 CHAR ),
PROJECT_NO               VARCHAR2 ( 4000 CHAR ),
PUNCH_LIST_STATUS        VARCHAR2 ( 4000 CHAR ),
P_ITR_LIST               VARCHAR2 ( 4000 CHAR ),
P_ITR_STATUS             VARCHAR2 ( 4000 CHAR ),
SERVICE                  VARCHAR2 ( 4000 CHAR ),
SERVICE_DESCRIPTION      VARCHAR2 ( 4000 CHAR ),
SINGLE_LINE_DIAGRAM      VARCHAR2 ( 4000 CHAR ),
SITE_NO                  VARCHAR2 ( 4000 CHAR ),
TAG_STATUS               VARCHAR2 ( 4000 CHAR ),
TAG_TYPE_LV1             VARCHAR2 ( 4000 CHAR ),
TAG_TYPE_LV2             VARCHAR2 ( 4000 CHAR ),
TEST_PACK                VARCHAR2 ( 4000 CHAR ),
TOTAL_AITR_COMPLETED     NUMBER,
TOTAL_A_ITR              NUMBER,
TOTAL_BITR_COMPLETED     NUMBER,
TOTAL_B_ITR              NUMBER,
TOTAL_PITR_COMPLETED     NUMBER,
TOTAL_PLI                NUMBER,
TOTAL_PLI_COMPLETED      NUMBER,
TOTAL_P_ITR              NUMBER,
TOTAL_VITR_COMPLETED     NUMBER,
TOTAL_V_ITR              NUMBER,
TO_DESCRIPTION           NUMBER,
TO_DRAWING               VARCHAR2 ( 4000 CHAR ),
TO_TAG                   VARCHAR2 ( 4000 CHAR ),
UNIT                     VARCHAR2 ( 4000 CHAR ),
VENDOR                   VARCHAR2 ( 4000 CHAR ),
VENDOR_INSTALLED         VARCHAR2 ( 4000 CHAR ),
V_ITR_LIST               VARCHAR2 ( 4000 CHAR ),
V_ITR_STATUS             VARCHAR2 ( 4000 CHAR ),
WBS_CODE                 VARCHAR2 ( 4000 CHAR ),
WORK_PACK                VARCHAR2 ( 4000 CHAR ),
ZONE                     VARCHAR2 ( 4000 CHAR )
);

/* ELECTRICAL TAG DETAILS - DIMENSION */
CREATE TABLE TAG_DETAILS_E (
ID  NUMBER NOT NULL PRIMARY KEY, 
TAG_ID                             NUMBER NOT NULL REFERENCES TAGS ( ID ),
VENDOR_ITEM                        VARCHAR2 ( 4000 CHAR ),
ACTUATOR_DETAIL                    VARCHAR2 ( 4000 CHAR ),
AMPERES_PER_HOUR_RATING            VARCHAR2 ( 4000 CHAR ),
DOC_HEATER_DTL                     VARCHAR2 ( 4000 CHAR ),
BEARING_DTL                        VARCHAR2 ( 4000 CHAR ),
BLOCK_DIAGRAM                      VARCHAR2 ( 4000 CHAR ),
CERTIFICATE_NUMBER                 VARCHAR2 ( 4000 CHAR ),
CERTIFYING_AUTHORITY               VARCHAR2 ( 4000 CHAR ),
CONTACTOR_RATING                   VARCHAR2 ( 4000 CHAR ),
CONTACTOR_RATING_UOM               VARCHAR2 ( 4000 CHAR ),
CONTACTOR_TYPE                     VARCHAR2 ( 4000 CHAR ),
CORROSION_GROUP                    VARCHAR2 ( 4000 CHAR ),
CRITICALITY_RATING                 VARCHAR2 ( 4000 CHAR ),
CURRENT_RATING                     VARCHAR2 ( 4000 CHAR ),
CURRENT_RATING_UOM                 VARCHAR2 ( 4000 CHAR ),
DATA_SHEET                         VARCHAR2 ( 4000 CHAR ),
EARTHING_DETAIL                    VARCHAR2 ( 4000 CHAR ),
EQUIPMENT_LEVEL_A_C                VARCHAR2 ( 4000 CHAR ),
DOC_PARTS_LIST                     VARCHAR2 ( 4000 CHAR ),
MOTOR_FRAME_SIZE                   VARCHAR2 ( 4000 CHAR ),
ELEC_FREQUENCY                     VARCHAR2 ( 4000 CHAR ),
ELEC_FREQUENCY_UOM                 VARCHAR2 ( 4000 CHAR ),
FULL_LOAD_CURRENT                  VARCHAR2 ( 4000 CHAR ),
FULL_LOAD_CURRENT_UOM              VARCHAR2 ( 4000 CHAR ),
FUSE_RATING                        VARCHAR2 ( 4000 CHAR ),
FUSE_RATING_UOM                    VARCHAR2 ( 4000 CHAR ),
FUSE_TYPE                          VARCHAR2 ( 4000 CHAR ),
HAZARDOUS_AREA_CLASSIFICATION      VARCHAR2 ( 4000 CHAR ),
INGRESS_PROTECTION_RATING          VARCHAR2 ( 4000 CHAR ),
INSULATION_CLASS                   VARCHAR2 ( 4000 CHAR ),
KVA_RATING                         VARCHAR2 ( 4000 CHAR ),
KVA_RATING_UOM                     VARCHAR2 ( 4000 CHAR ),
KW_RATING                          VARCHAR2 ( 4000 CHAR ),
KW_RATING_UOM                      VARCHAR2 ( 4000 CHAR ),
LAYOUT_DRAWING                     VARCHAR2 ( 4000 CHAR ),
LIFTING_DRAWING                    VARCHAR2 ( 4000 CHAR ),
LOCATION_PLAN                      VARCHAR2 ( 4000 CHAR ),
LUBRICATION_DETAILS                VARCHAR2 ( 4000 CHAR ),
MOTOR_POWER_RATING                 VARCHAR2 ( 4000 CHAR ),
MOTOR_POWER_RATING_UOM             VARCHAR2 ( 4000 CHAR ),
NAME_PLATE_VOLTAGE                 VARCHAR2 ( 4000 CHAR ),
NAME_PLATE_VOLTAGE_UOM             VARCHAR2 ( 4000 CHAR ),
ONE_LINE_DIAGRAM                   VARCHAR2 ( 4000 CHAR ),
OVERLOAD_RATING                    VARCHAR2 ( 4000 CHAR ),
OVERLOAD_RATING_UOM                VARCHAR2 ( 4000 CHAR ),
OVERLOAD_TYPE                      VARCHAR2 ( 4000 CHAR ),
PACKAGE_TAG                        VARCHAR2 ( 4000 CHAR ),
PARENT_TAG                         VARCHAR2 ( 4000 CHAR ),
PERFORMANCE_CURVE                  VARCHAR2 ( 4000 CHAR ),
PHASE                              VARCHAR2 ( 4000 CHAR ),
PURCHASE_ORDER_NUMBER              VARCHAR2 ( 4000 CHAR ),
RECOMMENDED_SPARE_PARTS_LIST       VARCHAR2 ( 4000 CHAR ),
ROUTING_DRAWING                    VARCHAR2 ( 4000 CHAR ),
SCHEMATIC_DIAGRAM                  VARCHAR2 ( 4000 CHAR ),
SERIAL_NUMBER                      VARCHAR2 ( 4000 CHAR ),
SERVICE_DESCRIPTION                VARCHAR2 ( 4000 CHAR ),
SPECIAL_TOOLS_LIST                 VARCHAR2 ( 4000 CHAR ),
SPEED                              VARCHAR2 ( 4000 CHAR ),
SPEED_UOM                          VARCHAR2 ( 4000 CHAR ),
SWITCHGEAR_PROTECTION_RATING       VARCHAR2 ( 4000 CHAR ),
TORQUE_SETTING                     VARCHAR2 ( 4000 CHAR ),
TOTAL_VOLTAGE                      VARCHAR2 ( 4000 CHAR ),
TOTAL_VOLTAGE_UOM                  VARCHAR2 ( 4000 CHAR ),
TRANSFORMER_RATIOS                 VARCHAR2 ( 4000 CHAR ),
VENDOR                             VARCHAR2 ( 4000 CHAR ),
VENDOR_MODEL_NUMBER                VARCHAR2 ( 4000 CHAR ),
VOLTAGE_RATING                     VARCHAR2 ( 4000 CHAR ),
VOLTAGE_RATING_UOM                 VARCHAR2 ( 4000 CHAR ),
WARRANTY_EXPIRATION                VARCHAR2 ( 4000 CHAR ),
WEIGHT_DRY_EMPTY                   VARCHAR2 ( 4000 CHAR ),
WEIGHT_DRY_EMPTY_UOM               VARCHAR2 ( 4000 CHAR ),
WEIGHT_OPERATING                   VARCHAR2 ( 4000 CHAR ),
WEIGHT_OPERATING_UOM               VARCHAR2 ( 4000 CHAR ),
WIRING_DIAGRAM                     VARCHAR2 ( 4000 CHAR )
);

/* PIPING LINE DETAILS - DIMENSION */
CREATE TABLE TAG_DETAILS_P ( 
ID  NUMBER NOT NULL PRIMARY KEY, 
TAG_ID                             NUMBER NOT NULL REFERENCES TAGS ( ID ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ),
CRITICALITY_RATING                 VARCHAR2 ( 4000 CHAR ),
CORROSION_GROUP                    VARCHAR2 ( 4000 CHAR ),
NOMINAL_SIZE                       VARCHAR2 ( 4000 CHAR ),
NOMINAL_SIZE_UOM                   VARCHAR2 ( 4000 CHAR ),
SCHEDULE                           VARCHAR2 ( 4000 CHAR ),
SERVICE                            VARCHAR2 ( 4000 CHAR ),
LINE_SPECIFICATION                 VARCHAR2 ( 4000 CHAR ),
MATERIAL                           VARCHAR2 ( 4000 CHAR ),
MAWP                               VARCHAR2 ( 4000 CHAR ),
MAWP_UOM                           VARCHAR2 ( 4000 CHAR ),
DESIGN_PRES                        VARCHAR2 ( 4000 CHAR ),
DESIGN_PRES_UOM                    VARCHAR2 ( 4000 CHAR ),
OPER_PRES_MAX                      VARCHAR2 ( 4000 CHAR ),
OPER_PRES_MAX_UOM                  VARCHAR2 ( 4000 CHAR ),
OPER_PRES_NORM                     VARCHAR2 ( 4000 CHAR ),
OPER_PRES_NORM_UOM                 VARCHAR2 ( 4000 CHAR ),
OPER_PRES_MIN                      VARCHAR2 ( 4000 CHAR ),
OPER_PRES_MIN_UOM                  VARCHAR2 ( 4000 CHAR ),
OPER_TEMP_MAX                      VARCHAR2 ( 4000 CHAR ),
OPER_TEMP_MAX_UOM                  VARCHAR2 ( 4000 CHAR ),
OPER_TEMP_NORM                     VARCHAR2 ( 4000 CHAR ),
OPER_TEMP_NORM_UOM                 VARCHAR2 ( 4000 CHAR ),
OPER_TEMP_MIN                      VARCHAR2 ( 4000 CHAR ),
OPER_TEMP_MIN_UOM                  VARCHAR2 ( 4000 CHAR ),
MDMT                               VARCHAR2 ( 4000 CHAR ),
MDMT_UOM                           VARCHAR2 ( 4000 CHAR ),
TRACE_HEAT_TEMP_MIN                VARCHAR2 ( 4000 CHAR ),
TRACE_HEAT_TEMP_MIN_UOM            VARCHAR2 ( 4000 CHAR ),
TRACE_HEAT_TEMP_MAX                VARCHAR2 ( 4000 CHAR ),
TRACE_HEAT_TEMP_MAX_UOM            VARCHAR2 ( 4000 CHAR ),
PRES_TEST_MEDIUM                   VARCHAR2 ( 4000 CHAR ),
PRES_TEST_PRES                     VARCHAR2 ( 4000 CHAR ),
PRES_TEST_PRES_UOM                 VARCHAR2 ( 4000 CHAR ),
LEAK_TEST_MEDIUM                   VARCHAR2 ( 4000 CHAR ),
LEAK_TEST_PRES                     VARCHAR2 ( 4000 CHAR ),
LEAK_TEST_PRES_UOM                 VARCHAR2 ( 4000 CHAR ),
INSUL_MATL                         VARCHAR2 ( 4000 CHAR ),
INSUL_SPEC                         VARCHAR2 ( 4000 CHAR ),
INSUL_THICKNESS                    VARCHAR2 ( 4000 CHAR ),
INSUL_THICKNESS_UOM                VARCHAR2 ( 4000 CHAR ),
CORROSION_ALLOWANCE                VARCHAR2 ( 4000 CHAR ),
POST_WELD_HEAT_TREATMENT           VARCHAR2 ( 4000 CHAR ),
NDT_TYPE                           VARCHAR2 ( 4000 CHAR ),
NDT_REQUIREMENT                    VARCHAR2 ( 4000 CHAR ),
COATING_REQUIREMENT                VARCHAR2 ( 4000 CHAR )
);

/* TELECOMMUNICATIONS TAG DETAILS - DIMENSION */
CREATE TABLE TAG_DETAILS_T (
ID  NUMBER NOT NULL PRIMARY KEY, 
TAG_ID               NUMBER NOT NULL REFERENCES TAGS ( ID ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ) ,
CABLE_TYPE                    VARCHAR2 ( 4000 CHAR ),
CERTIFICATE_NUMBER            VARCHAR2 ( 4000 CHAR ),
CERTIFYING_AUTHORITY          VARCHAR2 ( 4000 CHAR ),
CORROSION_GROUP               VARCHAR2 ( 4000 CHAR ),
CRITICALITY_RATING            VARCHAR2 ( 4000 CHAR ),
DATA_SHEET                    VARCHAR2 ( 4000 CHAR ),
DELETED_FLAG                  VARCHAR2 ( 4000 CHAR ),
EQUIPMENT_LEVEL_A_C           VARCHAR2 ( 4000 CHAR ),
LIC_FREQUENCY                 VARCHAR2 ( 4000 CHAR ),
FREQUENCY_UOM                 VARCHAR2 ( 4000 CHAR ),
INSTALLATION_DRAWING          VARCHAR2 ( 4000 CHAR ),
RF_LICENSE_FREQUENCY          VARCHAR2 ( 4000 CHAR ),
RF_LICENSE_FREQUENCY_UOM      VARCHAR2 ( 4000 CHAR ),
RF_LICSNSE_EFFECTIVE_ON       VARCHAR2 ( 4000 CHAR ),
RF_LICSNSE_EXPIRES_ON         VARCHAR2 ( 4000 CHAR ),
LOOP_TYPE                     VARCHAR2 ( 4000 CHAR ),
LOUD_SPEAKER_TRIP_SETTINGS    VARCHAR2 ( 4000 CHAR ),
POWER_RATING                  VARCHAR2 ( 4000 CHAR ),
POWER_RATING_UOM              VARCHAR2 ( 4000 CHAR ),
POWER_SUPPLY_TYPE             VARCHAR2 ( 4000 CHAR ),
POWER_SUPPLY_VOLTAGE          VARCHAR2 ( 4000 CHAR ),
POWER_SUPPLY_CURRENT          VARCHAR2 ( 4000 CHAR )
);

/* MECHANICAL TAG DETAILS - DIMENSION */
CREATE TABLE TAG_DETAILS_M (
ID  NUMBER NOT NULL PRIMARY KEY, 
TAG_ID               NUMBER NOT NULL REFERENCES TAGS ( ID ),
IS_DELETED           NUMBER ( 1 ) DEFAULT 0 CHECK ( IS_DELETED IN ( 0 , 1 ) ) ,
CAPACITY                           VARCHAR2 ( 4000 CHAR ),
CAPACITY_UOM                       VARCHAR2 ( 4000 CHAR ),
CERTIFICATE_NUMBER                 VARCHAR2 ( 4000 CHAR ),
CERTIFICATION_DATE                 VARCHAR2 ( 4000 CHAR ),
CERTIFICATION_REQUIREMENTS         VARCHAR2 ( 4000 CHAR ),
CONNECTION_RATING                  VARCHAR2 ( 4000 CHAR ),
CONNECTION_SIZE                    VARCHAR2 ( 4000 CHAR ),
CONNECTION_SIZE_UOM                VARCHAR2 ( 4000 CHAR ),
CORROSION_ALLOWANCE                VARCHAR2 ( 4000 CHAR ),
CORROSION_PROTECTION               VARCHAR2 ( 4000 CHAR ),
CORROSION_GROUP                    VARCHAR2 ( 4000 CHAR ),
COUPLING_DETAIL                    VARCHAR2 ( 4000 CHAR ),
CRITICALITY_RATING                 VARCHAR2 ( 4000 CHAR ),
CROSS_SECTIONAL_DRAWING            VARCHAR2 ( 4000 CHAR ),
DATA_SHEET                         VARCHAR2 ( 4000 CHAR ),
DESIGN_TEMP                        VARCHAR2 ( 4000 CHAR ),
DESIGN_TEMP_UOM                    VARCHAR2 ( 4000 CHAR ),
DESIGN_PRES                        VARCHAR2 ( 4000 CHAR ),
DESIGN_PRES_UOM                    VARCHAR2 ( 4000 CHAR ),
OPER_PRES_MAX                      VARCHAR2 ( 4000 CHAR ),
OPER_PRES_MAX_UOM                  VARCHAR2 ( 4000 CHAR ),
OPER_PRES_NORM                     VARCHAR2 ( 4000 CHAR ),
OPER_PRES_NORM_UOM                 VARCHAR2 ( 4000 CHAR ),
OPER_PRES_MIN                      VARCHAR2 ( 4000 CHAR ),
OPER_PRES_MIN_UOM                  VARCHAR2 ( 4000 CHAR ),
OPER_TEMP_MAX                      VARCHAR2 ( 4000 CHAR ),
OPER_TEMP_MAX_UOM                  VARCHAR2 ( 4000 CHAR ),
OPER_TEMP_NORM                     VARCHAR2 ( 4000 CHAR ),
OPER_TEMP_NORM_UOM                 VARCHAR2 ( 4000 CHAR ),
OPER_TEMP_MIN                      VARCHAR2 ( 4000 CHAR ),
OPER_TEMP_MIN_UOM                  VARCHAR2 ( 4000 CHAR ),
MDMT                               VARCHAR2 ( 4000 CHAR ),
MDMT_UOM                           VARCHAR2 ( 4000 CHAR ),
TRACE_HEAT_TEMP_MIN                VARCHAR2 ( 4000 CHAR ),
TRACE_HEAT_TEMP_MIN_UOM            VARCHAR2 ( 4000 CHAR ),
TRACE_HEAT_TEMP_MAX                VARCHAR2 ( 4000 CHAR ),
TRACE_HEAT_TEMP_MAX_UOM            VARCHAR2 ( 4000 CHAR ),
PRES_TEST_MEDIUM                   VARCHAR2 ( 4000 CHAR ),
PRES_TEST_PRES                     VARCHAR2 ( 4000 CHAR ),
PRES_TEST_PRES_UOM                 VARCHAR2 ( 4000 CHAR ),
LEAK_TEST_MEDIUM                   VARCHAR2 ( 4000 CHAR ),
LEAK_TEST_PRES                     VARCHAR2 ( 4000 CHAR ),
LEAK_TEST_PRES_UOM                 VARCHAR2 ( 4000 CHAR ),
INSUL_TYPE                         VARCHAR2 ( 4000 CHAR ),
INSUL_MATL                         VARCHAR2 ( 4000 CHAR ),
INSUL_SPEC                         VARCHAR2 ( 4000 CHAR ),
INSUL_THICKNESS                    VARCHAR2 ( 4000 CHAR ),
INSUL_THICKNESS_UOM                VARCHAR2 ( 4000 CHAR ),
POST_WELD_HEAT_TREATMENT           VARCHAR2 ( 4000 CHAR ),
NDT_TYPE                           VARCHAR2 ( 4000 CHAR ),
NDT_REQUIREMENT                    VARCHAR2 ( 4000 CHAR ),
COATING_REQUIREMENT                VARCHAR2 ( 4000 CHAR ),
DRIVER_TAG                         VARCHAR2 ( 4000 CHAR ),
DRIVER_TYPE                        VARCHAR2 ( 4000 CHAR ),
ELEMENT_DETAIL                     VARCHAR2 ( 4000 CHAR ),
ELEVATION_DRAWING                  VARCHAR2 ( 4000 CHAR ),
EQUIPMENT_LEVEL_A_C           VARCHAR2 ( 4000 CHAR ),
EQUIPMENT_PARTS_LIST               VARCHAR2 ( 4000 CHAR ),
GASKET_TYPE                        VARCHAR2 ( 4000 CHAR ),
GENERAL_ARRANGEMENT_DRAWING        VARCHAR2 ( 4000 CHAR ),
HAZARDOUS_AREA_CLASSIFICATION      VARCHAR2 ( 4000 CHAR ),
HYDROSTATIC_TEST_PRESSURE          VARCHAR2 ( 4000 CHAR ),
HYDROSTATIC_TEST_PRESSURE_UOM      VARCHAR2 ( 4000 CHAR ),
ISOMETRIC_DRAWING                  VARCHAR2 ( 4000 CHAR ),
LAYOUT_DRAWING                     VARCHAR2 ( 4000 CHAR ),
LIFTING_DRAWING                    VARCHAR2 ( 4000 CHAR ),
LIFTING_EQUIPMENT                  VARCHAR2 ( 4000 CHAR ),
LOCATION                           VARCHAR2 ( 4000 CHAR ),
LOCATION_PLAN                      VARCHAR2 ( 4000 CHAR ),
MANUFACTURER                       VARCHAR2 ( 4000 CHAR ),
MANUFACTURER_MODEL_NUMBER          VARCHAR2 ( 4000 CHAR ),
MATERIAL                           VARCHAR2 ( 4000 CHAR ),
MAWP                               VARCHAR2 ( 4000 CHAR ),
MAWP_UOM                           VARCHAR2 ( 4000 CHAR ),
MAWT                               VARCHAR2 ( 4000 CHAR ),
MAWT_UOM                           VARCHAR2 ( 4000 CHAR ),
NACE_REQUIREMENT                   VARCHAR2 ( 4000 CHAR ),
NUMBER_OF_STAGES                   VARCHAR2 ( 4000 CHAR ),
NUMBER_OF_TUBES                    VARCHAR2 ( 4000 CHAR ),
OPERATING_SPEED                    VARCHAR2 ( 4000 CHAR ),
OPERATING_SPEED_UOM                VARCHAR2 ( 4000 CHAR ),
PACKAGE_TAG                        VARCHAR2 ( 4000 CHAR ),
PARENT_TAG                         VARCHAR2 ( 4000 CHAR ),
PEAK_LOAD                          VARCHAR2 ( 4000 CHAR ),
PEAK_LOAD_UOM                      VARCHAR2 ( 4000 CHAR ),
PERFORMANCE_CURVE                  VARCHAR2 ( 4000 CHAR ),
PROCESS_FLOW_DIAGRAM               VARCHAR2 ( 4000 CHAR ),
PURCHASE_ORDER_NUMBER              VARCHAR2 ( 4000 CHAR ),
RECOMMENDED_SPARE_PARTS_LIST       VARCHAR2 ( 4000 CHAR ),
ROTATION                           VARCHAR2 ( 4000 CHAR ),
SEAL_DETAILS                       VARCHAR2 ( 4000 CHAR ),
SERIAL_NUMBER                      VARCHAR2 ( 4000 CHAR ),
SERVICE_DESCRIPTION                VARCHAR2 ( 4000 CHAR ),
SPECIAL_TOOLS_LIST                 VARCHAR2 ( 4000 CHAR ),
SPECIFIC_GRAVITY                   VARCHAR2 ( 4000 CHAR ),
SUB_LOCATION                       VARCHAR2 ( 4000 CHAR ),
SUB_SYSTEM                         VARCHAR2 ( 4000 CHAR ),
SWL                                VARCHAR2 ( 4000 CHAR ),
SWL_UOM                            VARCHAR2 ( 4000 CHAR ),
SYSTEM                             VARCHAR2 ( 4000 CHAR ),
TEMA_CLASS                         VARCHAR2 ( 4000 CHAR ),
TEST_LOAD                          VARCHAR2 ( 4000 CHAR ),
TEST_LOAD_UOM                      VARCHAR2 ( 4000 CHAR ),
TEST_PRESSURE                      VARCHAR2 ( 4000 CHAR ),
TEST_PRESSURE_UOM                  VARCHAR2 ( 4000 CHAR ),
TEST_REQUIREMENTS                  VARCHAR2 ( 4000 CHAR ),
TUBESIDE_DESIGN_TEMP        VARCHAR2 ( 4000 CHAR ),
TUBESIDE_DESIGN_TEMP_UOM    VARCHAR2 ( 4000 CHAR ),
TUBE_BUNDLE_WEIGHT                 VARCHAR2 ( 4000 CHAR ),
TUBE_BUNDLE_WEIGHT_UOM             VARCHAR2 ( 4000 CHAR ),
TUBE_TEST_PRESSURE                 VARCHAR2 ( 4000 CHAR ),
TUBE_TEST_PRESSURE_UOM             VARCHAR2 ( 4000 CHAR ),
VENDOR                             VARCHAR2 ( 4000 CHAR ),
VENDOR_ITEM                        VARCHAR2 ( 4000 CHAR ),
VENDOR_MODEL_NUMBER                VARCHAR2 ( 4000 CHAR ),
VESSEL_DESIGN_CODE                 VARCHAR2 ( 4000 CHAR ),
VESSEL_DESIGN_CALCULATION          VARCHAR2 ( 4000 CHAR ),
VESSEL_DETAIL_DRAWING              VARCHAR2 ( 4000 CHAR ),
VESSEL_DIAMETER                    VARCHAR2 ( 4000 CHAR ),
VESSEL_DIAMETER_UOM                VARCHAR2 ( 4000 CHAR ),
VESSEL_LEN_OVERALL                 VARCHAR2 ( 4000 CHAR ),
VESSEL_LEN_OVERALL_UOM             VARCHAR2 ( 4000 CHAR ),
VESSEL_LEN_TT                      VARCHAR2 ( 4000 CHAR ),
VESSEL_LEN_TT_UOM                  VARCHAR2 ( 4000 CHAR ),
WARRANTY_EXPIRATION                VARCHAR2 ( 4000 CHAR ),
WEIGHT_DRY_EMPTY                   VARCHAR2 ( 4000 CHAR ),
WEIGHT_DRY_EMPTY_UOM               VARCHAR2 ( 4000 CHAR ),
WEIGHT_OPERATING                   VARCHAR2 ( 4000 CHAR ),
WEIGHT_OPERATING_UOM               VARCHAR2 ( 4000 CHAR ),
WCE_CERT_DATE                      VARCHAR2 ( 4000 CHAR ),
WCE_CERT_NUMBER                    VARCHAR2 ( 4000 CHAR )
);
